Parameters:
  EC2InstanceType:
    Default: t2.micro
    Description: EC2 instance type on which IDE runs
    Type: String
  AutoHibernateTimeout:
    Default: 30
    Description: How many minutes idle before shutting down the IDE
    Type: Number
  SubnetIdentifier:
    Description: SubnetId
    Type: AWS::EC2::Subnet::Id
  S3BucketName:
    Default: tests3bucket
    Description: S3 bucket name (must be unique, use youe first+last+date)
    Type: String
    
Resources:
  IDE:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Repositories:
      - RepositoryUrl: https://github.com/aws-samples/cfn101-workshop.git
        PathComponent: github.com/aws-samples/cfn101-workshop
      Description: Cloud9 IDE
      AutomaticStopTimeMinutes:
        Ref: AutoHibernateTimeout
      SubnetId:
        Ref: SubnetIdentifier
      InstanceType:
        Ref: EC2InstanceType
      Name:
        Ref: AWS::StackName
    
  S3:        
    Type: AWS::S3::Bucket
    Properties: 
        BucketName: 
            Ref: S3BucketName

Outputs:
  Cloud9URL:
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/cloud9/home/environments/
        - Ref: IDE
    Description: Cloud9 environment
  S3:
    Value: !Ref S3
    Description: S3 bucket name
  S3ARN:
    Value: !GetAtt S3.Arn
    Description: S3 bucket name